# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myapplication-gl

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://glacrdemo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_11a0e170449f4e9393fd7910a3cac6e2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4b1ca4e94d6b4df49a37fa7bde5e608b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: glacrdemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_11a0e170449f4e9393fd7910a3cac6e2 }}/webimage:${{ github.sha }}
        context: dotnet

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myapplication-gl'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_56b1c50efefd4e7e8c639ebadabb0e30 }}
        images: 'glacrdemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_11a0e170449f4e9393fd7910a3cac6e2 }}/webimage:${{ github.sha }}'
